### ISSUE TITLE
Help!! no acepta el codigo

### ISSUE THREAD

**Issue by JosephSaenz** [mgp25/WART#15]
podrian ayudarme, al poner el codigo me sale este error "Verification code not accepted"
Les quedo agradecido por la respuesta

**Comment by JosephSaenz** [comment]
Les quedo agradecido por la respuesta

**Comment by mgp25** [comment]
@JosephSaenz try the post in english, so everyone can read and find an answer to the question.

You must request and register using the same WART (in order to have the same identity). Also the code has an expiration time, so be sure you registered in time.

If you want, provide debug log and information so we can help you better.

Regards

**Comment by JosephSaenz** [comment]
thanks use the latest version WART-1.8.1.0 and it worked.
thanks for everything
